package edu.wxc.book.domain;

public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_item.item_id
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_item.apply_id
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    private Integer applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_item.course_title
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    private String courseTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_item.isbn
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    private String isbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_item.book_name
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_item.author
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_item.press
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    private String press;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_item.publish_time
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    private String publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_item.book_category
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    private String bookCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_item.major_grade
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    private String majorGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_item.student_number
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    private Integer studentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_item.teacher_book
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    private String teacherBook;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_item.total_number
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    private Integer totalNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_item.remark
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_item.item_id
     *
     * @return the value of excel_item.item_id
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_item.item_id
     *
     * @param itemId the value for excel_item.item_id
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_item.apply_id
     *
     * @return the value of excel_item.apply_id
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public Integer getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_item.apply_id
     *
     * @param applyId the value for excel_item.apply_id
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public void setApplyId(Integer applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_item.course_title
     *
     * @return the value of excel_item.course_title
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public String getCourseTitle() {
        return courseTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_item.course_title
     *
     * @param courseTitle the value for excel_item.course_title
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public void setCourseTitle(String courseTitle) {
        this.courseTitle = courseTitle == null ? null : courseTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_item.isbn
     *
     * @return the value of excel_item.isbn
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_item.isbn
     *
     * @param isbn the value for excel_item.isbn
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_item.book_name
     *
     * @return the value of excel_item.book_name
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_item.book_name
     *
     * @param bookName the value for excel_item.book_name
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_item.author
     *
     * @return the value of excel_item.author
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_item.author
     *
     * @param author the value for excel_item.author
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_item.press
     *
     * @return the value of excel_item.press
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public String getPress() {
        return press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_item.press
     *
     * @param press the value for excel_item.press
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public void setPress(String press) {
        this.press = press == null ? null : press.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_item.publish_time
     *
     * @return the value of excel_item.publish_time
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public String getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_item.publish_time
     *
     * @param publishTime the value for excel_item.publish_time
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public void setPublishTime(String publishTime) {
        this.publishTime = publishTime == null ? null : publishTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_item.book_category
     *
     * @return the value of excel_item.book_category
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public String getBookCategory() {
        return bookCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_item.book_category
     *
     * @param bookCategory the value for excel_item.book_category
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public void setBookCategory(String bookCategory) {
        this.bookCategory = bookCategory == null ? null : bookCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_item.major_grade
     *
     * @return the value of excel_item.major_grade
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public String getMajorGrade() {
        return majorGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_item.major_grade
     *
     * @param majorGrade the value for excel_item.major_grade
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public void setMajorGrade(String majorGrade) {
        this.majorGrade = majorGrade == null ? null : majorGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_item.student_number
     *
     * @return the value of excel_item.student_number
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public Integer getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_item.student_number
     *
     * @param studentNumber the value for excel_item.student_number
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public void setStudentNumber(Integer studentNumber) {
        this.studentNumber = studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_item.teacher_book
     *
     * @return the value of excel_item.teacher_book
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public String getTeacherBook() {
        return teacherBook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_item.teacher_book
     *
     * @param teacherBook the value for excel_item.teacher_book
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public void setTeacherBook(String teacherBook) {
        this.teacherBook = teacherBook == null ? null : teacherBook.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_item.total_number
     *
     * @return the value of excel_item.total_number
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public Integer getTotalNumber() {
        return totalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_item.total_number
     *
     * @param totalNumber the value for excel_item.total_number
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public void setTotalNumber(Integer totalNumber) {
        this.totalNumber = totalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_item.remark
     *
     * @return the value of excel_item.remark
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_item.remark
     *
     * @param remark the value for excel_item.remark
     *
     * @mbg.generated Mon Jun 25 19:46:00 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    @Override
    public String toString() {
        return "Item{" +
                "itemId=" + itemId +
                ", applyId=" + applyId +
                ", courseTitle='" + courseTitle + '\'' +
                ", isbn='" + isbn + '\'' +
                ", bookName='" + bookName + '\'' +
                ", author='" + author + '\'' +
                ", press='" + press + '\'' +
                ", publishTime='" + publishTime + '\'' +
                ", bookCategory='" + bookCategory + '\'' +
                ", majorGrade='" + majorGrade + '\'' +
                ", studentNumber=" + studentNumber +
                ", teacherBook='" + teacherBook + '\'' +
                ", totalNumber=" + totalNumber +
                ", remark='" + remark + '\'' +
                '}';
    }
}