package edu.wxc.book.domain;

public class Major {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.major_id
     *
     * @mbg.generated Thu Jul 05 16:25:32 CST 2018
     */
    private Integer majorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.academy_id
     *
     * @mbg.generated Thu Jul 05 16:25:32 CST 2018
     */
    private Integer academyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.major_name
     *
     * @mbg.generated Thu Jul 05 16:25:32 CST 2018
     */
    private String majorName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.major_id
     *
     * @return the value of major.major_id
     *
     * @mbg.generated Thu Jul 05 16:25:32 CST 2018
     */
    public Integer getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.major_id
     *
     * @param majorId the value for major.major_id
     *
     * @mbg.generated Thu Jul 05 16:25:32 CST 2018
     */
    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.academy_id
     *
     * @return the value of major.academy_id
     *
     * @mbg.generated Thu Jul 05 16:25:32 CST 2018
     */
    public Integer getAcademyId() {
        return academyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.academy_id
     *
     * @param academyId the value for major.academy_id
     *
     * @mbg.generated Thu Jul 05 16:25:32 CST 2018
     */
    public void setAcademyId(Integer academyId) {
        this.academyId = academyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.major_name
     *
     * @return the value of major.major_name
     *
     * @mbg.generated Thu Jul 05 16:25:32 CST 2018
     */
    public String getMajorName() {
        return majorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.major_name
     *
     * @param majorName the value for major.major_name
     *
     * @mbg.generated Thu Jul 05 16:25:32 CST 2018
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName == null ? null : majorName.trim();
    }
}